### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by cjessett** [GeorgiosAlexakis/jammming#1]
(Important) [This](https://github.com/GeorgiosAlexakis/jammming/blob/dca3b253181287fcad2fecc24dbc9be5b73afba0/src/util/Spotify.js#L1) should be stored in an environment variable. There is a section in the readme on how to do that.

**Comment by GeorgiosAlexakis** [comment]
Done.
I am now also storing the hostname and port number in environment variables.
