### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by cjessett** [GeorgiosAlexakis/jammming#2]
(Simplify) [Here](https://github.com/GeorgiosAlexakis/jammming/blob/dca3b253181287fcad2fecc24dbc9be5b73afba0/src/util/Spotify.js#L68-L69) you should use `.catch` to handle errors a promise returns.

**Comment by GeorgiosAlexakis** [comment]
Though there was nothing wrong with the ES6 fetch request and error handling, I have now changed it to a ES8 request with a try catch block for consistency.
